services:

  herokumodel:
    image: heroku-model
    pull_policy: never
    container_name: heroku-model
    build:
      context: . #/english
      dockerfile: Dockerfile
      #target: runner
    ports:
      - 80:80
    #env_file:
    #  - ./backend/.env
    #depends_on:
    #  - mongodb
    




