services:

  english:
    image: greeting-english
    pull_policy: never
    container_name: greeting-english
    build:
      context: ./english
      dockerfile: Dockerfile
      #target: runner
    ports:
      - 80:80
    #env_file:
    #  - ./backend/.env
    #depends_on:
    #  - mongodb
    
  italian:
    image: greeting-italian
    pull_policy: never
    container_name: greeting-italian
    build:
      context: ./italian
      dockerfile: Dockerfile
      #target: runner
    ports:
      - 8000:8000

  kamba:
    image: greeting-kamba
    pull_policy: never
    container_name: greeting-kamba
    build:
      context: ./kamba
      dockerfile: Dockerfile
      #target: runner
    ports:
      - 8081:8081
   
  swahili:
    image: greeting-swahili
    pull_policy: never
    container_name: greeting-swahili
    build:
      context: ./swahili
      dockerfile: Dockerfile
      #target: runner
    ports:
      - 8082:8082

  #frontend:
  
  #mongodb:
  
  #mongo-express:

#volumes:
#  mongodb-data:

